### ISSUE TITLE
Reboot the reboot

### ISSUE THREAD

**Issue by mattpilott** [neuekit/neuekit#18]
```css
/*----------------------------------------------------------------------------*\

    #REBOOT BROWSER STYLES

    - Version:      1.1
    - Author:       Creative Little Dots
    - Site:         http://creativelittle.uk/reboot
    - Copyright:    2017, Creative Little Dots
    – License:      MIT | http://goo.gl/p3bexl
    - Mentions:     Based on sanitize https://goo.gl/a3DzGd

\*----------------------------------------------------------------------------*/

/*----------------------------------------------------------------------------*\
    1. Remove repeating backgrounds in all browsers (opinionated).
    2. Add box sizing inheritence in all browsers (opinionated).
    3. Add relative positioning (opinionated).
\*----------------------------------------------------------------------------*/

*,
::before,
::after {
    background-repeat: no-repeat;   /* 1 */
    box-sizing: inherit;            /* 2 */
    position: relative;             /* 3 */
}



/*----------------------------------------------------------------------------*\
    1. Add text decoration inheritance in all browsers (opinionated).
    2. Add vertical alignment inheritence in all browsers (opinionated).
\*----------------------------------------------------------------------------*/

::before,
::after {
    text-decoration: inherit;   /* 1 */
    vertical-align: inherit;    /* 2 */
}



/*----------------------------------------------------------------------------*\
    1. Add border box sizing in all browsers (opinionated).
    2. Add the default cursor in all browsers (opinionated).
    3. Add a flattened line height in all browsers (opinionated).
    4. Prevent font size adjustments after orientation changes in IE and iOS.
\*----------------------------------------------------------------------------*/

html {
    box-sizing: border-box;             /* 1 */
    cursor: default;                    /* 2 */
    line-height: 1.75;                  /* 3 */
    -ms-text-size-adjust: 100%;         /* 4 */
    -webkit-text-size-adjust: 100%;     /* 4 */
}



/*----------------------------------------------------------------------------*\
    Remove the margin in all browsers (opinionated).
\*----------------------------------------------------------------------------*/

body,
optgroup {
    margin: 0;
}



/*----------------------------------------------------------------------------*\
    1. Add correct display in Edge, IE, & Firefox.
\*----------------------------------------------------------------------------*/

article,
aside,
details,
figcaption,
figure,
footer,
header,
main,
menu,
nav,
section {
    display: block;
}



/*----------------------------------------------------------------------------*\
    Add the correct display in all browsers.
\*----------------------------------------------------------------------------*/

summary {
    display: list-item;
}



/*----------------------------------------------------------------------------*\
    Add the correct display in IE.
\*----------------------------------------------------------------------------*/

template {
    display: none;
}



/*----------------------------------------------------------------------------*\
    Correct the font sizes and margins on `h1` elements within `section` and
    `article` contexts in Chrome, Firefox, and Safari
\*----------------------------------------------------------------------------*/

h1 {
    font-size: 2em;
    margin: 0.6875em 0;
}



/*----------------------------------------------------------------------------*\
    1. Correct font sizing inheritance and scaling in all browsers.
    2. Correct the odd `em` font sizing in all browsers.
\*----------------------------------------------------------------------------*/

code,
kbd,
pre,
samp {
    font-family: monospace, monospace;  /* 1 */
    font-size: 1em;                     /* 2 */
}



/*----------------------------------------------------------------------------*\
    1. Add the correct box sizing in Firefox.
    2. Show the overflow in Edge and IE.
\*----------------------------------------------------------------------------*/

hr {
    box-sizing: content-box; /* 1 */
    height: 0; /* 1 */
    overflow: visible; /* 2 */
}



/*----------------------------------------------------------------------------*\
    Add the correct font weight in Chrome, Edge, and Safari.
\*----------------------------------------------------------------------------*/

b,
strong {
    font-weight: bolder;
}



/*----------------------------------------------------------------------------*\
    Add the correct font style in Android 4.3-.
\*----------------------------------------------------------------------------*/

dfn {
    font-style: italic;
}



/*----------------------------------------------------------------------------*\
    Add the correct vertical alignment in Chrome, Firefox, and Opera.
\*----------------------------------------------------------------------------*/

progress {
    vertical-align: baseline;
}



/*----------------------------------------------------------------------------*\
    Correct the font size in all browsers.
\*----------------------------------------------------------------------------*/

small {
    font-size: 83.3333%;
}


/*----------------------------------------------------------------------------*\
    In all browsers (opinionated).
    1. Correct the font size in all browsers.
\*----------------------------------------------------------------------------*/

sub,
sup {
    font-size: 83.3333%; /* 1 */
    line-height: 0;
    vertical-align: baseline;
}

sub {
    bottom: -0.25em;
}

sup {
    top: -0.5em;
}



/*----------------------------------------------------------------------------*\
    Remove the text shadow on text selections (opinionated).
    1. Restore the coloring undone by defining the text shadow (opinionated).
\*----------------------------------------------------------------------------*/

%selection {
    background-color: #b3d4fc;  /* 1 */
    color: #000000;             /* 1 */
    text-shadow: none;
}

::-moz-selection {
    @extend %selection;
}

::selection {
    @extend %selection;
}



/*----------------------------------------------------------------------------*\
    Change the alignment on media elements in all browers (opinionated).
\*----------------------------------------------------------------------------*/

audio,
canvas,
iframe,
img,
svg,
video {
    vertical-align: middle;
}



/*----------------------------------------------------------------------------*\
    Change the fill color to match the text color in all browsers (opinionated).
\*----------------------------------------------------------------------------*/

svg {
    fill: currentColor;
}



/*----------------------------------------------------------------------------*\
    Remove border spacing in all browsers (opinionated).
\*----------------------------------------------------------------------------*/

table {
    border-collapse: collapse;
}



/*----------------------------------------------------------------------------*\
    Remove the inner border and padding in Firefox.
\*----------------------------------------------------------------------------*/

::-moz-focus-inner {
    border-style: none;
    padding: 0;
}



/*----------------------------------------------------------------------------*\
    Correct the border, margin, and padding in all browsers.
\*----------------------------------------------------------------------------*/

fieldset {
    border: 1px solid #c0c0c0;
    margin: 0 2px;
    padding: 0.35em 0.625em 0.75em;
}



/*----------------------------------------------------------------------------*\
    1. Correct the text wrapping in Edge and IE.
    2. Remove the padding so developers are not caught out when they zero out
       `fieldset` elements in all browsers.
    3. Correct the color inheritance from `fieldset` elements in IE.
\*----------------------------------------------------------------------------*/

legend {
    color: inherit;         /* 3 */
    display: table;         /* 1 */
    max-width: 100%;        /* 1 */
    padding: 0;             /* 2 */
    white-space: normal;    /* 1 */
}



/*----------------------------------------------------------------------------*\
    1. Remove the vertical scrollbar in IE.
    2. Change the resize direction on textareas in all browsers (opinionated).
\*----------------------------------------------------------------------------*/

textarea {
    overflow: auto;     /* 1 */
    resize: vertical;   /* 2 */
}



/*----------------------------------------------------------------------------*\
    Correct the cursor style on increment and decrement buttons in Chrome.
\*----------------------------------------------------------------------------*/

::-webkit-inner-spin-button,
::-webkit-outer-spin-button {
    height: auto;
}



/*----------------------------------------------------------------------------*\
    Remove the inner padding and cancel buttons in Chrome and Safari for macOS.
\*----------------------------------------------------------------------------*/

::-webkit-search-cancel-button,
::-webkit-search-decoration {
    -webkit-appearance: none;
}



/*----------------------------------------------------------------------------*\
    Correct the text style on placeholders in Chrome, Edge, and Safari.
\*----------------------------------------------------------------------------*/

::-webkit-input-placeholder {
    color: inherit;
    opacity: 0.5;
}



/*----------------------------------------------------------------------------*\
    1. Correct the inability to style clickable types in iOS and Safari.
    2. Change font properties to `inherit` in Safari.
\*----------------------------------------------------------------------------*/

::-webkit-file-upload-button {
    -webkit-appearance: button;     /* 1 */
    font: inherit;                  /* 2 */
}



/*----------------------------------------------------------------------------*\
    1. Remove the gray background on active links in IE 10.
    2. Remove the gaps in underlines in iOS 8+ and Safari 8+.
\*----------------------------------------------------------------------------*/

a {
    background-color: transparent;          /* 1 */
    -webkit-text-decoration-skip: objects;  /* 2 */
}



/*----------------------------------------------------------------------------*\
    Remove the tapping delay on clickable elements (opinionated).
    1. Remove the tapping delay in IE 10.
\*----------------------------------------------------------------------------*/

a,
area,
button,
input,
label,
select,
textarea,
[tabindex] {
    -ms-touch-action: manipulation; /* 1 */
    touch-action: manipulation;
}



/*----------------------------------------------------------------------------*\
    1. Remove the default styling in all browsers (opinionated).
    2. Remove the margin in Firefox and Safari.
\*----------------------------------------------------------------------------*/

button,
input,
select,
textarea {
    background-color: transparent;  /* 1 */
    border-style: none;             /* 1 */
    color: inherit;                 /* 1 */
    font-size: inherit;             /* 1 */
    line-height: inherit;           /* 1 */
    margin: 0;                      /* 2 */
}



/*----------------------------------------------------------------------------*\
    Correct the overflow in IE.
    1. Correct the overflow in Edge
\*----------------------------------------------------------------------------*/

button,
input { /* 1 */
    overflow: visible;
}



/*----------------------------------------------------------------------------*\
    Remove the inheritance in Edge, Firefox, and IE.
    1. Remove the inheritance in Firefox.
\*----------------------------------------------------------------------------*/

button,
select { /* 1 */
    text-transform: none;
}



/*----------------------------------------------------------------------------*\
    1. Prevent the WebKit bug where (2) destroys native `audio` and `video`
       controls in Android 4.
    2. Correct the inability to style clickable types in iOS and Safari.
\*----------------------------------------------------------------------------*/

button,
[type="button"],                    /* 1 */
[type="reset"],
[type="submit"] {
    -webkit-appearance: button;     /* 2 */
}



/*----------------------------------------------------------------------------*\
    Correct the focus styles unset by the previous rule.
\*----------------------------------------------------------------------------*/

:-moz-focusring {
    outline: 1px dotted ButtonText;
}



/*----------------------------------------------------------------------------*\
    1. Correct the odd appearance in Chrome and Safari.
    2. Correct the outline style in Safari
\*----------------------------------------------------------------------------*/

[type="search"] {
    -webkit-appearance: textfield;  /* 1 */
    outline-offset: -2px;           /* 2 */
}



/*----------------------------------------------------------------------------*\
    Change the cursor on busy elements (opinionated).
\*----------------------------------------------------------------------------*/

[aria-busy="true"] {
    cursor: progress;
}



/*----------------------------------------------------------------------------*\
    Change the cursor on control elements (opinionated).
\*----------------------------------------------------------------------------*/

[aria-controls] {
    cursor: pointer;
}



/*----------------------------------------------------------------------------*\
    Change the cursor on disabled, not-editable, or otherwise inoperable
    elements (opinionated).
\*----------------------------------------------------------------------------*/

[aria-disabled] {
    cursor: default;
}


/*----------------------------------------------------------------------------*\
    Remove the outline when hovering in all browsers (opinionated).
\*----------------------------------------------------------------------------*/

a:hover {
    outline-width: 0;
}



/*----------------------------------------------------------------------------*\
    1. Remove the bottom border in Firefox 39-.
    2. Add the correct text decoration in Chrome, Edge, IE, Opera, and Safari.
\*----------------------------------------------------------------------------*/

abbr[title] {
    border-bottom: none; /* 1 */
    text-decoration: underline; /* 2 */
    text-decoration: underline dotted; /* 2 */
}



/*----------------------------------------------------------------------------*\
    Remove the list style on navigation lists in all browsers (opinionated).
\*----------------------------------------------------------------------------*/

nav ol,
nav ul {
    list-style: none;
}



/*----------------------------------------------------------------------------*\
    Hide the overflow in IE.
\*----------------------------------------------------------------------------*/

svg:not(:root) {
    overflow: hidden;
}



/*----------------------------------------------------------------------------*\
    Change the display on visually hidden accessible elements (opinionated).
\*----------------------------------------------------------------------------*/

[hidden][aria-hidden="false"] {
    clip: rect(0, 0, 0, 0);
    display: inherit;
    position: absolute;
}

[hidden][aria-hidden="false"]:focus {
    clip: auto;
}


```
